# Generated by Django 5.0.14 on 2025-07-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0004_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='current_saved_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
